import "@/app/ui/globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "@/app/ui/components.css";
import Header1 from "@/components/header1";
import { Analytics } from "@vercel/analytics/react";
import BaiDuAnalytics from "@/app/BaiDuAnalytics";
import GoogleAnalytics from "@/app/GoogleAnalytics";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-white">
          <Header1 color="light" />
          {children}
        </div>
        <BaiDuAnalytics />
          {/* <Analytics /> */}
        {/* <GoogleAnalytics/> */}
      </body>
    </html>
  );
}
