import "@/app/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "@/app/ui/components.css";
import Header1 from "@/components/Header1"
import { usePathname } from 'next/navigation';
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  metadata: {
    title: string;
    description: string;
  };
};
export default function RootLayout({
  children,metadata
}: RootLayoutProps) {
  console.log(metadata)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white">
          <Header1 color="light"/>
          {children}
        </div>
      </body>
    </html>
  );
}
